package jerly.datastructure;

/**
 * The input question/word that we want to analyze.
 * 
 * @author  Laszlo Szathmary (<a href="szathmar@loria.fr">szathmar@loria.fr</a>)
 */
public class Question
{
   /**
    * The question that we want to analyze if it can be generated by
    * the rules or not.
    */
   private String question;

   /**
    * Sets the question.
    * 
    * @param question The question we want to set.
    */
   public void setQuestion(String question) {
      this.question = question;
   }
   
   /**
    * @return The question.
    */
   public String getQuestion() {
      return this.question;
   }
   
   /**
    * @return Length of the question.
    */
   public int getLength() {
      return this.question.length();
   }

   /**
    * @return String representation of the question. 
    */
   public String toString() {
      return this.question;
   }

   /**
    * The question is composed of terminal letters!
    * We want to get one of its letters at position "pos".
    * 
    * @param pos Which terminal letter of the question we want to get.
    * @return Terminal letter of the question at the given position.
    */
   public Terminal getLetter(int pos)
   {
      // indexing of pos starts with 1. So if pos==1, it means the 0th element.
      return (new Terminal(this.question.charAt(pos-1)));
   }
}
